name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build OAuth
      run: docker build . --file src/Skoruba.Duende.IdentityServer.Admin/Dockerfile --tag oauth:$(date +%s)
    - name: Build SSO
      run: docker build . --file src/Skoruba.Duende.IdentityServer.Admin.Api/Dockerfile --tag sso:$(date +%s)
    - name: Build OApi
      run: docker build . --file src/Skoruba.Duende.IdentityServer.STS.Identity/Dockerfile --tag oapi:$(date +%s)
